title: Every. Damn. Day.
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.08441809192299843
  brandStrength: 0
  lightness: 0.3766488078981638
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  rhythmicContrast: 0.04515929147601128
typography_spectrum: 0.3978092689067125
description: Refined Excellence
layout_spectrum: 1
name: '#champing'
